export const barangays = [
  { city: "Iligan", label: "Iligan" },
<<<<<<< HEAD
  { city: "Iligan", label: "Cebu" },
  { city: "Iligan", label: "Abuno" },
  { city: "Iligan", label: "Acmac" },
  { city: "Iligan", label: "Bagong Silang" },
  { city: "Iligan", label: "Bonbonon" },
  { city: "Iligan", label: "Bunawan" },
  { city: "Iligan", label: "Buru-un" },
  { city: "Iligan", label: "Dalipuga" },
  { city: "Iligan", label: "Digkilaan" },
  { city: "Iligan", label: "Ditucalan" },
  { city: "Iligan", label: "Hinaplanon" },
  { city: "Iligan", label: "Kabacsanan" },
  { city: "Iligan", label: "Kalilangan" },
  { city: "Iligan", label: "Kiwalan" },
  { city: "Iligan", label: "Lanipao" },
  { city: "Iligan", label: "Luinab" },
  { city: "Iligan", label: "Mahayahay" },
  { city: "Iligan", label: "Mainit" },
  { city: "Iligan", label: "Mandulog" },
  { city: "Iligan", label: "Maria Cristina" },
  { city: "Iligan", label: "Pala-o" },
  { city: "Iligan", label: "Panoroganan" },
  { city: "Iligan", label: "Poblacion" },
  { city: "Iligan", label: "Santiago" },
  { city: "Iligan", label: "Santo Rosario" },
  { city: "Iligan", label: "Suarez" },
  { city: "Iligan", label: "Tambacan" },
  { city: "Iligan", label: "Tubod" },
  { city: "Iligan", label: "Ubaldo Laya" },
  { city: "Tubod", label: "Poblacion" },
  { city: "Tubod", label: "Libertad" },
  { city: "Tubod", label: "Mago-ong" },
  { city: "Tubod", label: "Aurora" },
  { city: "Tubod", label: "San Isidro" },
  { city: "Tubod", label: "Maranding" },
  { city: "Tubod", label: "Maranding Annex" },
  { city: "Tubod", label: "Maria Cristina" },
  { city: "Tubod", label: "Rizal" },
  { city: "Tubod", label: "Gatas" },
  { city: "Tubod", label: "Mahayahay" },
  { city: "Tubod", label: "Taytayan" },
  { city: "Tubod", label: "Nibunga" },
  { city: "Tubod", label: "Sagadan" },
  { city: "Tubod", label: "Imelda" },
  { city: "Tubod", label: "Maguindanao" },
=======
  // { city: "Iligan", label: "Cebu" },
  // { city: "Iligan", label: "Abuno" },
  // { city: "Iligan", label: "Acmac" },
  // { city: "Iligan", label: "Bagong Silang" },
  { city: "Lanao del Norte", label: "Lanao del Norte" },
  // { city: "Lanao del Norte", label: "Libertad" },
  // { city: "Lanao del Norte", label: "Mago-ong" },
  // { city: "Lanao del Norte", label: "Aurora" },
  // { city: "Lanao del Norte", label: "San Isidro" },
  // { city: "Lanao del Norte", label: "Maranding" },
  // { city: "Lanao del Norte", label: "Maranding Annex" },
  // { city: "Lanao del Norte", label: "Maria Cristina" },
  // { city: "Lanao del Norte", label: "Rizal" },
  // { city: "Lanao del Norte", label: "Gatas" },
  // { city: "Lanao del Norte", label: "Mahayahay" },
  // { city: "Lanao del Norte", label: "Taytayan" },
  // { city: "Lanao del Norte", label: "Nibunga" },
  // { city: "Lanao del Norte", label: "Sagadan" },
  // { city: "Lanao del Norte", label: "Imelda" },
  // { city: "Lanao del Norte", label: "Maguindanao" },
>>>>>>> 886ab8f (fix: page filters)
];
